MODULE UTIL_ELEC_PARAM_T_MOD

USE MODD_ELEC_PARAM, ONLY : ELEC_PARAM_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_ELEC_PARAM_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_ELEC_PARAM_T
END INTERFACE







CONTAINS

SUBROUTINE ACDC_SAVE_ELEC_PARAM_T (SELF, KLUN)

IMPLICIT NONE
TYPE (ELEC_PARAM_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%XFCI
WRITE (KLUN) SELF%XFQSEDC
WRITE (KLUN) SELF%XEXQSEDC
WRITE (KLUN) SELF%XFQSEDR
WRITE (KLUN) SELF%XEXQSEDR
WRITE (KLUN) SELF%XFQSEDI
WRITE (KLUN) SELF%XEXQSEDI
WRITE (KLUN) SELF%XFQSEDS
WRITE (KLUN) SELF%XEXQSEDS
WRITE (KLUN) SELF%XFQSEDG
WRITE (KLUN) SELF%XEXQSEDG
WRITE (KLUN) SELF%XFQSEDH
WRITE (KLUN) SELF%XEXQSEDH
WRITE (KLUN) SELF%XEGMIN
WRITE (KLUN) SELF%XEGMAX
WRITE (KLUN) SELF%XESMIN
WRITE (KLUN) SELF%XESMAX
WRITE (KLUN) SELF%XEIMIN
WRITE (KLUN) SELF%XEIMAX
WRITE (KLUN) SELF%XECMIN
WRITE (KLUN) SELF%XECMAX
WRITE (KLUN) SELF%XERMIN
WRITE (KLUN) SELF%XERMAX
WRITE (KLUN) SELF%XEHMIN
WRITE (KLUN) SELF%XEHMAX
WRITE (KLUN) SELF%XFQUPDC
WRITE (KLUN) SELF%XFQUPDR
WRITE (KLUN) SELF%XFQUPDI
WRITE (KLUN) SELF%XEXFQUPDI
WRITE (KLUN) SELF%XFQUPDS
WRITE (KLUN) SELF%XFQUPDG
WRITE (KLUN) SELF%XFQUPDH
WRITE (KLUN) SELF%XFQSED
WRITE (KLUN) SELF%XDQ
END SUBROUTINE

SUBROUTINE ACDC_LOAD_ELEC_PARAM_T (SELF, KLUN)

IMPLICIT NONE
TYPE (ELEC_PARAM_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%XFCI
READ (KLUN) SELF%XFQSEDC
READ (KLUN) SELF%XEXQSEDC
READ (KLUN) SELF%XFQSEDR
READ (KLUN) SELF%XEXQSEDR
READ (KLUN) SELF%XFQSEDI
READ (KLUN) SELF%XEXQSEDI
READ (KLUN) SELF%XFQSEDS
READ (KLUN) SELF%XEXQSEDS
READ (KLUN) SELF%XFQSEDG
READ (KLUN) SELF%XEXQSEDG
READ (KLUN) SELF%XFQSEDH
READ (KLUN) SELF%XEXQSEDH
READ (KLUN) SELF%XEGMIN
READ (KLUN) SELF%XEGMAX
READ (KLUN) SELF%XESMIN
READ (KLUN) SELF%XESMAX
READ (KLUN) SELF%XEIMIN
READ (KLUN) SELF%XEIMAX
READ (KLUN) SELF%XECMIN
READ (KLUN) SELF%XECMAX
READ (KLUN) SELF%XERMIN
READ (KLUN) SELF%XERMAX
READ (KLUN) SELF%XEHMIN
READ (KLUN) SELF%XEHMAX
READ (KLUN) SELF%XFQUPDC
READ (KLUN) SELF%XFQUPDR
READ (KLUN) SELF%XFQUPDI
READ (KLUN) SELF%XEXFQUPDI
READ (KLUN) SELF%XFQUPDS
READ (KLUN) SELF%XFQUPDG
READ (KLUN) SELF%XFQUPDH
READ (KLUN) SELF%XFQSED
READ (KLUN) SELF%XDQ
END SUBROUTINE













END MODULE
