MODULE UTIL_RAIN_ICE_DESCR_T_MOD

USE MODD_RAIN_ICE_DESCR_N, ONLY : RAIN_ICE_DESCR_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_RAIN_ICE_DESCR_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_RAIN_ICE_DESCR_T
END INTERFACE







CONTAINS

SUBROUTINE ACDC_SAVE_RAIN_ICE_DESCR_T (SELF, KLUN)

IMPLICIT NONE
TYPE (RAIN_ICE_DESCR_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LXRTMIN
WRITE (KLUN) SELF%XCEXVT
WRITE (KLUN) SELF%XAC
WRITE (KLUN) SELF%XBC
WRITE (KLUN) SELF%XCC
WRITE (KLUN) SELF%XDC
WRITE (KLUN) SELF%XAR
WRITE (KLUN) SELF%XBR
WRITE (KLUN) SELF%XCR
WRITE (KLUN) SELF%XDR
WRITE (KLUN) SELF%XCCR
WRITE (KLUN) SELF%XF0R
WRITE (KLUN) SELF%XF1R
WRITE (KLUN) SELF%XC1R
WRITE (KLUN) SELF%XAI
WRITE (KLUN) SELF%XBI
WRITE (KLUN) SELF%XC_I
WRITE (KLUN) SELF%XDI
WRITE (KLUN) SELF%XF0I
WRITE (KLUN) SELF%XF2I
WRITE (KLUN) SELF%XC1I
WRITE (KLUN) SELF%XAS
WRITE (KLUN) SELF%XBS
WRITE (KLUN) SELF%XCS
WRITE (KLUN) SELF%XDS
WRITE (KLUN) SELF%XCCS
WRITE (KLUN) SELF%XCXS
WRITE (KLUN) SELF%XF0S
WRITE (KLUN) SELF%XF1S
WRITE (KLUN) SELF%XC1S
WRITE (KLUN) SELF%XAG
WRITE (KLUN) SELF%XBG
WRITE (KLUN) SELF%XCG
WRITE (KLUN) SELF%XDG
WRITE (KLUN) SELF%XCCG
WRITE (KLUN) SELF%XCXG
WRITE (KLUN) SELF%XF0G
WRITE (KLUN) SELF%XF1G
WRITE (KLUN) SELF%XC1G
WRITE (KLUN) SELF%XAH
WRITE (KLUN) SELF%XBH
WRITE (KLUN) SELF%XCH
WRITE (KLUN) SELF%XDH
WRITE (KLUN) SELF%XCCH
WRITE (KLUN) SELF%XCXH
WRITE (KLUN) SELF%XF0H
WRITE (KLUN) SELF%XF1H
WRITE (KLUN) SELF%XC1H
WRITE (KLUN) SELF%XALPHAC
WRITE (KLUN) SELF%XNUC
WRITE (KLUN) SELF%XALPHAC2
WRITE (KLUN) SELF%XNUC2
WRITE (KLUN) SELF%XLBEXC
WRITE (KLUN) SELF%XLBC
WRITE (KLUN) SELF%XALPHAR
WRITE (KLUN) SELF%XNUR
WRITE (KLUN) SELF%XLBEXR
WRITE (KLUN) SELF%XLBR
WRITE (KLUN) SELF%XALPHAI
WRITE (KLUN) SELF%XNUI
WRITE (KLUN) SELF%XLBEXI
WRITE (KLUN) SELF%XLBI
WRITE (KLUN) SELF%XALPHAS
WRITE (KLUN) SELF%XNUS
WRITE (KLUN) SELF%XLBEXS
WRITE (KLUN) SELF%XLBS
WRITE (KLUN) SELF%XNS
WRITE (KLUN) SELF%XALPHAG
WRITE (KLUN) SELF%XNUG
WRITE (KLUN) SELF%XLBEXG
WRITE (KLUN) SELF%XLBG
WRITE (KLUN) SELF%XALPHAH
WRITE (KLUN) SELF%XNUH
WRITE (KLUN) SELF%XLBEXH
WRITE (KLUN) SELF%XLBH
WRITE (KLUN) SELF%XFVELOS
WRITE (KLUN) SELF%XTRANS_MP_GAMMAS
WRITE (KLUN) SELF%XLBDAR_MAX
WRITE (KLUN) SELF%XLBDAS_MIN
WRITE (KLUN) SELF%XLBDAS_MAX
WRITE (KLUN) SELF%XLBDAG_MAX
LXRTMIN = ALLOCATED (SELF%XRTMIN)
WRITE (KLUN) LXRTMIN
IF (LXRTMIN) THEN
  WRITE (KLUN) LBOUND (SELF%XRTMIN)
  WRITE (KLUN) UBOUND (SELF%XRTMIN)
  WRITE (KLUN) SELF%XRTMIN
ENDIF
WRITE (KLUN) SELF%XCONC_SEA
WRITE (KLUN) SELF%XCONC_LAND
WRITE (KLUN) SELF%XCONC_URBAN
END SUBROUTINE

SUBROUTINE ACDC_LOAD_RAIN_ICE_DESCR_T (SELF, KLUN)

IMPLICIT NONE
TYPE (RAIN_ICE_DESCR_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LXRTMIN
READ (KLUN) SELF%XCEXVT
READ (KLUN) SELF%XAC
READ (KLUN) SELF%XBC
READ (KLUN) SELF%XCC
READ (KLUN) SELF%XDC
READ (KLUN) SELF%XAR
READ (KLUN) SELF%XBR
READ (KLUN) SELF%XCR
READ (KLUN) SELF%XDR
READ (KLUN) SELF%XCCR
READ (KLUN) SELF%XF0R
READ (KLUN) SELF%XF1R
READ (KLUN) SELF%XC1R
READ (KLUN) SELF%XAI
READ (KLUN) SELF%XBI
READ (KLUN) SELF%XC_I
READ (KLUN) SELF%XDI
READ (KLUN) SELF%XF0I
READ (KLUN) SELF%XF2I
READ (KLUN) SELF%XC1I
READ (KLUN) SELF%XAS
READ (KLUN) SELF%XBS
READ (KLUN) SELF%XCS
READ (KLUN) SELF%XDS
READ (KLUN) SELF%XCCS
READ (KLUN) SELF%XCXS
READ (KLUN) SELF%XF0S
READ (KLUN) SELF%XF1S
READ (KLUN) SELF%XC1S
READ (KLUN) SELF%XAG
READ (KLUN) SELF%XBG
READ (KLUN) SELF%XCG
READ (KLUN) SELF%XDG
READ (KLUN) SELF%XCCG
READ (KLUN) SELF%XCXG
READ (KLUN) SELF%XF0G
READ (KLUN) SELF%XF1G
READ (KLUN) SELF%XC1G
READ (KLUN) SELF%XAH
READ (KLUN) SELF%XBH
READ (KLUN) SELF%XCH
READ (KLUN) SELF%XDH
READ (KLUN) SELF%XCCH
READ (KLUN) SELF%XCXH
READ (KLUN) SELF%XF0H
READ (KLUN) SELF%XF1H
READ (KLUN) SELF%XC1H
READ (KLUN) SELF%XALPHAC
READ (KLUN) SELF%XNUC
READ (KLUN) SELF%XALPHAC2
READ (KLUN) SELF%XNUC2
READ (KLUN) SELF%XLBEXC
READ (KLUN) SELF%XLBC
READ (KLUN) SELF%XALPHAR
READ (KLUN) SELF%XNUR
READ (KLUN) SELF%XLBEXR
READ (KLUN) SELF%XLBR
READ (KLUN) SELF%XALPHAI
READ (KLUN) SELF%XNUI
READ (KLUN) SELF%XLBEXI
READ (KLUN) SELF%XLBI
READ (KLUN) SELF%XALPHAS
READ (KLUN) SELF%XNUS
READ (KLUN) SELF%XLBEXS
READ (KLUN) SELF%XLBS
READ (KLUN) SELF%XNS
READ (KLUN) SELF%XALPHAG
READ (KLUN) SELF%XNUG
READ (KLUN) SELF%XLBEXG
READ (KLUN) SELF%XLBG
READ (KLUN) SELF%XALPHAH
READ (KLUN) SELF%XNUH
READ (KLUN) SELF%XLBEXH
READ (KLUN) SELF%XLBH
READ (KLUN) SELF%XFVELOS
READ (KLUN) SELF%XTRANS_MP_GAMMAS
READ (KLUN) SELF%XLBDAR_MAX
READ (KLUN) SELF%XLBDAS_MIN
READ (KLUN) SELF%XLBDAS_MAX
READ (KLUN) SELF%XLBDAG_MAX
READ (KLUN) LXRTMIN
IF (LXRTMIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XRTMIN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XRTMIN
ENDIF
READ (KLUN) SELF%XCONC_SEA
READ (KLUN) SELF%XCONC_LAND
READ (KLUN) SELF%XCONC_URBAN
END SUBROUTINE













END MODULE
