MODULE UTIL_PARAM_ICE_T_MOD

USE MODD_PARAM_ICE_N, ONLY : PARAM_ICE_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_PARAM_ICE_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_PARAM_ICE_T
END INTERFACE







CONTAINS

SUBROUTINE ACDC_SAVE_PARAM_ICE_T (SELF, KLUN)

IMPLICIT NONE
TYPE (PARAM_ICE_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LWARM
WRITE (KLUN) SELF%LSEDIC
WRITE (KLUN) SELF%LDEPOSC
WRITE (KLUN) SELF%XVDEPOSC
WRITE (KLUN) SELF%CPRISTINE_ICE
WRITE (KLUN) SELF%CSEDIM
WRITE (KLUN) SELF%LRED
WRITE (KLUN) SELF%LFEEDBACKT
WRITE (KLUN) SELF%LEVLIMIT
WRITE (KLUN) SELF%LNULLWETG
WRITE (KLUN) SELF%LWETGPOST
WRITE (KLUN) SELF%LNULLWETH
WRITE (KLUN) SELF%LWETHPOST
WRITE (KLUN) SELF%CSNOWRIMING
WRITE (KLUN) SELF%XFRACM90
WRITE (KLUN) SELF%NMAXITER_MICRO
WRITE (KLUN) SELF%XMRSTEP
WRITE (KLUN) SELF%LCONVHG
WRITE (KLUN) SELF%LCRFLIMIT
WRITE (KLUN) SELF%XTSTEP_TS
WRITE (KLUN) SELF%CSUBG_RC_RR_ACCR
WRITE (KLUN) SELF%CSUBG_RR_EVAP
WRITE (KLUN) SELF%CSUBG_PR_PDF
WRITE (KLUN) SELF%CSUBG_AUCV_RC
WRITE (KLUN) SELF%CSUBG_AUCV_RI
WRITE (KLUN) SELF%CSUBG_MF_PDF
WRITE (KLUN) SELF%LADJ_BEFORE
WRITE (KLUN) SELF%LADJ_AFTER
WRITE (KLUN) SELF%LSEDIM_AFTER
WRITE (KLUN) SELF%XSPLIT_MAXCFL
WRITE (KLUN) SELF%LSNOW_T
WRITE (KLUN) SELF%LPACK_INTERP
WRITE (KLUN) SELF%LPACK_MICRO
WRITE (KLUN) SELF%NPROMICRO
WRITE (KLUN) SELF%LCRIAUTI
WRITE (KLUN) SELF%XCRIAUTI_NAM
WRITE (KLUN) SELF%XT0CRIAUTI_NAM
WRITE (KLUN) SELF%XBCRIAUTI_NAM
WRITE (KLUN) SELF%XACRIAUTI_NAM
WRITE (KLUN) SELF%XCRIAUTC_NAM
WRITE (KLUN) SELF%XRDEPSRED_NAM
WRITE (KLUN) SELF%XRDEPGRED_NAM
WRITE (KLUN) SELF%LOCND2
WRITE (KLUN) SELF%LKOGAN
WRITE (KLUN) SELF%LMODICEDEP
WRITE (KLUN) SELF%LEXCLDROP
WRITE (KLUN) SELF%XFRMIN_NAM
END SUBROUTINE

SUBROUTINE ACDC_LOAD_PARAM_ICE_T (SELF, KLUN)

IMPLICIT NONE
TYPE (PARAM_ICE_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LWARM
READ (KLUN) SELF%LSEDIC
READ (KLUN) SELF%LDEPOSC
READ (KLUN) SELF%XVDEPOSC
READ (KLUN) SELF%CPRISTINE_ICE
READ (KLUN) SELF%CSEDIM
READ (KLUN) SELF%LRED
READ (KLUN) SELF%LFEEDBACKT
READ (KLUN) SELF%LEVLIMIT
READ (KLUN) SELF%LNULLWETG
READ (KLUN) SELF%LWETGPOST
READ (KLUN) SELF%LNULLWETH
READ (KLUN) SELF%LWETHPOST
READ (KLUN) SELF%CSNOWRIMING
READ (KLUN) SELF%XFRACM90
READ (KLUN) SELF%NMAXITER_MICRO
READ (KLUN) SELF%XMRSTEP
READ (KLUN) SELF%LCONVHG
READ (KLUN) SELF%LCRFLIMIT
READ (KLUN) SELF%XTSTEP_TS
READ (KLUN) SELF%CSUBG_RC_RR_ACCR
READ (KLUN) SELF%CSUBG_RR_EVAP
READ (KLUN) SELF%CSUBG_PR_PDF
READ (KLUN) SELF%CSUBG_AUCV_RC
READ (KLUN) SELF%CSUBG_AUCV_RI
READ (KLUN) SELF%CSUBG_MF_PDF
READ (KLUN) SELF%LADJ_BEFORE
READ (KLUN) SELF%LADJ_AFTER
READ (KLUN) SELF%LSEDIM_AFTER
READ (KLUN) SELF%XSPLIT_MAXCFL
READ (KLUN) SELF%LSNOW_T
READ (KLUN) SELF%LPACK_INTERP
READ (KLUN) SELF%LPACK_MICRO
READ (KLUN) SELF%NPROMICRO
READ (KLUN) SELF%LCRIAUTI
READ (KLUN) SELF%XCRIAUTI_NAM
READ (KLUN) SELF%XT0CRIAUTI_NAM
READ (KLUN) SELF%XBCRIAUTI_NAM
READ (KLUN) SELF%XACRIAUTI_NAM
READ (KLUN) SELF%XCRIAUTC_NAM
READ (KLUN) SELF%XRDEPSRED_NAM
READ (KLUN) SELF%XRDEPGRED_NAM
READ (KLUN) SELF%LOCND2
READ (KLUN) SELF%LKOGAN
READ (KLUN) SELF%LMODICEDEP
READ (KLUN) SELF%LEXCLDROP
READ (KLUN) SELF%XFRMIN_NAM
END SUBROUTINE













END MODULE
