MODULE UTIL_RAIN_ICE_PARAM_T_MOD

USE MODD_RAIN_ICE_PARAM_N, ONLY : RAIN_ICE_PARAM_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_RAIN_ICE_PARAM_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_RAIN_ICE_PARAM_T
END INTERFACE







CONTAINS

SUBROUTINE ACDC_SAVE_RAIN_ICE_PARAM_T (SELF, KLUN)

IMPLICIT NONE
TYPE (RAIN_ICE_PARAM_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LXGAMINC_RIM1, LXGAMINC_RIM2, LXGAMINC_RIM4, LXKER_GWETH, LXKER_RACCS, LXKER_RACCSS, LXKER_RDRYG, LXKER_RWETH, LXKER_SACCRG, LXKER_SDRYG
LOGICAL :: LXKER_SWETH
WRITE (KLUN) SELF%XFSEDC
WRITE (KLUN) SELF%XFSEDR
WRITE (KLUN) SELF%XEXSEDR
WRITE (KLUN) SELF%XFSEDI
WRITE (KLUN) SELF%XEXCSEDI
WRITE (KLUN) SELF%XEXRSEDI
WRITE (KLUN) SELF%XFSEDS
WRITE (KLUN) SELF%XEXSEDS
WRITE (KLUN) SELF%XFSEDG
WRITE (KLUN) SELF%XEXSEDG
WRITE (KLUN) SELF%XNU10
WRITE (KLUN) SELF%XALPHA1
WRITE (KLUN) SELF%XBETA1
WRITE (KLUN) SELF%XNU20
WRITE (KLUN) SELF%XALPHA2
WRITE (KLUN) SELF%XBETA2
WRITE (KLUN) SELF%XMNU0
WRITE (KLUN) SELF%XALPHA3
WRITE (KLUN) SELF%XBETA3
WRITE (KLUN) SELF%XHON
WRITE (KLUN) SELF%XSCFAC
WRITE (KLUN) SELF%X0EVAR
WRITE (KLUN) SELF%X1EVAR
WRITE (KLUN) SELF%XEX0EVAR
WRITE (KLUN) SELF%XEX1EVAR
WRITE (KLUN) SELF%X0DEPI
WRITE (KLUN) SELF%X2DEPI
WRITE (KLUN) SELF%X0DEPS
WRITE (KLUN) SELF%X1DEPS
WRITE (KLUN) SELF%XEX0DEPS
WRITE (KLUN) SELF%XEX1DEPS
WRITE (KLUN) SELF%XRDEPSRED
WRITE (KLUN) SELF%X0DEPG
WRITE (KLUN) SELF%X1DEPG
WRITE (KLUN) SELF%XEX0DEPG
WRITE (KLUN) SELF%XEX1DEPG
WRITE (KLUN) SELF%XRDEPGRED
WRITE (KLUN) SELF%XTIMAUTI
WRITE (KLUN) SELF%XTEXAUTI
WRITE (KLUN) SELF%XCRIAUTI
WRITE (KLUN) SELF%XT0CRIAUTI
WRITE (KLUN) SELF%XACRIAUTI
WRITE (KLUN) SELF%XBCRIAUTI
WRITE (KLUN) SELF%XCOLIS
WRITE (KLUN) SELF%XCOLEXIS
WRITE (KLUN) SELF%XFIAGGS
WRITE (KLUN) SELF%XEXIAGGS
WRITE (KLUN) SELF%XTIMAUTC
WRITE (KLUN) SELF%XCRIAUTC
WRITE (KLUN) SELF%XFCACCR
WRITE (KLUN) SELF%XEXCACCR
WRITE (KLUN) SELF%XDCSLIM
WRITE (KLUN) SELF%XCOLCS
WRITE (KLUN) SELF%XEXCRIMSS
WRITE (KLUN) SELF%XCRIMSS
WRITE (KLUN) SELF%XEXCRIMSG
WRITE (KLUN) SELF%XCRIMSG
WRITE (KLUN) SELF%XEXSRIMCG
WRITE (KLUN) SELF%XSRIMCG
WRITE (KLUN) SELF%XEXSRIMCG2
WRITE (KLUN) SELF%XSRIMCG2
WRITE (KLUN) SELF%XSRIMCG3
WRITE (KLUN) SELF%XGAMINC_BOUND_MIN
WRITE (KLUN) SELF%XGAMINC_BOUND_MAX
WRITE (KLUN) SELF%XRIMINTP1
WRITE (KLUN) SELF%XRIMINTP2
WRITE (KLUN) SELF%NGAMINC
LXGAMINC_RIM1 = ALLOCATED (SELF%XGAMINC_RIM1)
WRITE (KLUN) LXGAMINC_RIM1
IF (LXGAMINC_RIM1) THEN
  WRITE (KLUN) LBOUND (SELF%XGAMINC_RIM1)
  WRITE (KLUN) UBOUND (SELF%XGAMINC_RIM1)
  WRITE (KLUN) SELF%XGAMINC_RIM1
ENDIF
LXGAMINC_RIM2 = ALLOCATED (SELF%XGAMINC_RIM2)
WRITE (KLUN) LXGAMINC_RIM2
IF (LXGAMINC_RIM2) THEN
  WRITE (KLUN) LBOUND (SELF%XGAMINC_RIM2)
  WRITE (KLUN) UBOUND (SELF%XGAMINC_RIM2)
  WRITE (KLUN) SELF%XGAMINC_RIM2
ENDIF
LXGAMINC_RIM4 = ALLOCATED (SELF%XGAMINC_RIM4)
WRITE (KLUN) LXGAMINC_RIM4
IF (LXGAMINC_RIM4) THEN
  WRITE (KLUN) LBOUND (SELF%XGAMINC_RIM4)
  WRITE (KLUN) UBOUND (SELF%XGAMINC_RIM4)
  WRITE (KLUN) SELF%XGAMINC_RIM4
ENDIF
WRITE (KLUN) SELF%XFRACCSS
WRITE (KLUN) SELF%XLBRACCS1
WRITE (KLUN) SELF%XLBRACCS2
WRITE (KLUN) SELF%XLBRACCS3
WRITE (KLUN) SELF%XFSACCRG
WRITE (KLUN) SELF%XLBSACCR1
WRITE (KLUN) SELF%XLBSACCR2
WRITE (KLUN) SELF%XLBSACCR3
WRITE (KLUN) SELF%XACCLBDAS_MIN
WRITE (KLUN) SELF%XACCLBDAS_MAX
WRITE (KLUN) SELF%XACCLBDAR_MIN
WRITE (KLUN) SELF%XACCLBDAR_MAX
WRITE (KLUN) SELF%XACCINTP1S
WRITE (KLUN) SELF%XACCINTP2S
WRITE (KLUN) SELF%XACCINTP1R
WRITE (KLUN) SELF%XACCINTP2R
WRITE (KLUN) SELF%NACCLBDAS
WRITE (KLUN) SELF%NACCLBDAR
LXKER_RACCSS = ALLOCATED (SELF%XKER_RACCSS)
WRITE (KLUN) LXKER_RACCSS
IF (LXKER_RACCSS) THEN
  WRITE (KLUN) LBOUND (SELF%XKER_RACCSS)
  WRITE (KLUN) UBOUND (SELF%XKER_RACCSS)
  WRITE (KLUN) SELF%XKER_RACCSS
ENDIF
LXKER_RACCS = ALLOCATED (SELF%XKER_RACCS)
WRITE (KLUN) LXKER_RACCS
IF (LXKER_RACCS) THEN
  WRITE (KLUN) LBOUND (SELF%XKER_RACCS)
  WRITE (KLUN) UBOUND (SELF%XKER_RACCS)
  WRITE (KLUN) SELF%XKER_RACCS
ENDIF
LXKER_SACCRG = ALLOCATED (SELF%XKER_SACCRG)
WRITE (KLUN) LXKER_SACCRG
IF (LXKER_SACCRG) THEN
  WRITE (KLUN) LBOUND (SELF%XKER_SACCRG)
  WRITE (KLUN) UBOUND (SELF%XKER_SACCRG)
  WRITE (KLUN) SELF%XKER_SACCRG
ENDIF
WRITE (KLUN) SELF%XFSCVMG
WRITE (KLUN) SELF%XCOLIR
WRITE (KLUN) SELF%XEXRCFRI
WRITE (KLUN) SELF%XRCFRI
WRITE (KLUN) SELF%XEXICFRR
WRITE (KLUN) SELF%XICFRR
WRITE (KLUN) SELF%XFCDRYG
WRITE (KLUN) SELF%XCOLIG
WRITE (KLUN) SELF%XCOLEXIG
WRITE (KLUN) SELF%XFIDRYG
WRITE (KLUN) SELF%XFIDRYG2
WRITE (KLUN) SELF%XEXFIDRYG
WRITE (KLUN) SELF%XCOLSG
WRITE (KLUN) SELF%XCOLEXSG
WRITE (KLUN) SELF%XFSDRYG
WRITE (KLUN) SELF%XLBSDRYG1
WRITE (KLUN) SELF%XLBSDRYG2
WRITE (KLUN) SELF%XLBSDRYG3
WRITE (KLUN) SELF%XFRDRYG
WRITE (KLUN) SELF%XLBRDRYG1
WRITE (KLUN) SELF%XLBRDRYG2
WRITE (KLUN) SELF%XLBRDRYG3
WRITE (KLUN) SELF%XDRYLBDAR_MIN
WRITE (KLUN) SELF%XDRYLBDAR_MAX
WRITE (KLUN) SELF%XDRYLBDAS_MIN
WRITE (KLUN) SELF%XDRYLBDAS_MAX
WRITE (KLUN) SELF%XDRYLBDAG_MIN
WRITE (KLUN) SELF%XDRYLBDAG_MAX
WRITE (KLUN) SELF%XDRYINTP1R
WRITE (KLUN) SELF%XDRYINTP2R
WRITE (KLUN) SELF%XDRYINTP1S
WRITE (KLUN) SELF%XDRYINTP2S
WRITE (KLUN) SELF%XDRYINTP1G
WRITE (KLUN) SELF%XDRYINTP2G
WRITE (KLUN) SELF%NDRYLBDAR
WRITE (KLUN) SELF%NDRYLBDAS
WRITE (KLUN) SELF%NDRYLBDAG
LXKER_SDRYG = ALLOCATED (SELF%XKER_SDRYG)
WRITE (KLUN) LXKER_SDRYG
IF (LXKER_SDRYG) THEN
  WRITE (KLUN) LBOUND (SELF%XKER_SDRYG)
  WRITE (KLUN) UBOUND (SELF%XKER_SDRYG)
  WRITE (KLUN) SELF%XKER_SDRYG
ENDIF
LXKER_RDRYG = ALLOCATED (SELF%XKER_RDRYG)
WRITE (KLUN) LXKER_RDRYG
IF (LXKER_RDRYG) THEN
  WRITE (KLUN) LBOUND (SELF%XKER_RDRYG)
  WRITE (KLUN) UBOUND (SELF%XKER_RDRYG)
  WRITE (KLUN) SELF%XKER_RDRYG
ENDIF
WRITE (KLUN) SELF%XFSEDH
WRITE (KLUN) SELF%XEXSEDH
WRITE (KLUN) SELF%X0DEPH
WRITE (KLUN) SELF%X1DEPH
WRITE (KLUN) SELF%XEX0DEPH
WRITE (KLUN) SELF%XEX1DEPH
WRITE (KLUN) SELF%XCOLIH
WRITE (KLUN) SELF%XCOLEXIH
WRITE (KLUN) SELF%XCOLSH
WRITE (KLUN) SELF%XCOLEXSH
WRITE (KLUN) SELF%XCOLGH
WRITE (KLUN) SELF%XCOLEXGH
WRITE (KLUN) SELF%XFWETH
WRITE (KLUN) SELF%XFSWETH
WRITE (KLUN) SELF%XLBSWETH1
WRITE (KLUN) SELF%XLBSWETH2
WRITE (KLUN) SELF%XLBSWETH3
WRITE (KLUN) SELF%XFGWETH
WRITE (KLUN) SELF%XLBGWETH1
WRITE (KLUN) SELF%XLBGWETH2
WRITE (KLUN) SELF%XLBGWETH3
WRITE (KLUN) SELF%XFRWETH
WRITE (KLUN) SELF%XLBRWETH1
WRITE (KLUN) SELF%XLBRWETH2
WRITE (KLUN) SELF%XLBRWETH3
WRITE (KLUN) SELF%XWETLBDAS_MIN
WRITE (KLUN) SELF%XWETLBDAS_MAX
WRITE (KLUN) SELF%XWETLBDAG_MIN
WRITE (KLUN) SELF%XWETLBDAG_MAX
WRITE (KLUN) SELF%XWETLBDAR_MIN
WRITE (KLUN) SELF%XWETLBDAR_MAX
WRITE (KLUN) SELF%XWETLBDAH_MIN
WRITE (KLUN) SELF%XWETLBDAH_MAX
WRITE (KLUN) SELF%XWETINTP1S
WRITE (KLUN) SELF%XWETINTP2S
WRITE (KLUN) SELF%XWETINTP1G
WRITE (KLUN) SELF%XWETINTP2G
WRITE (KLUN) SELF%XWETINTP1R
WRITE (KLUN) SELF%XWETINTP2R
WRITE (KLUN) SELF%XWETINTP1H
WRITE (KLUN) SELF%XWETINTP2H
WRITE (KLUN) SELF%NWETLBDAS
WRITE (KLUN) SELF%NWETLBDAG
WRITE (KLUN) SELF%NWETLBDAR
WRITE (KLUN) SELF%NWETLBDAH
LXKER_SWETH = ALLOCATED (SELF%XKER_SWETH)
WRITE (KLUN) LXKER_SWETH
IF (LXKER_SWETH) THEN
  WRITE (KLUN) LBOUND (SELF%XKER_SWETH)
  WRITE (KLUN) UBOUND (SELF%XKER_SWETH)
  WRITE (KLUN) SELF%XKER_SWETH
ENDIF
LXKER_GWETH = ALLOCATED (SELF%XKER_GWETH)
WRITE (KLUN) LXKER_GWETH
IF (LXKER_GWETH) THEN
  WRITE (KLUN) LBOUND (SELF%XKER_GWETH)
  WRITE (KLUN) UBOUND (SELF%XKER_GWETH)
  WRITE (KLUN) SELF%XKER_GWETH
ENDIF
LXKER_RWETH = ALLOCATED (SELF%XKER_RWETH)
WRITE (KLUN) LXKER_RWETH
IF (LXKER_RWETH) THEN
  WRITE (KLUN) LBOUND (SELF%XKER_RWETH)
  WRITE (KLUN) UBOUND (SELF%XKER_RWETH)
  WRITE (KLUN) SELF%XKER_RWETH
ENDIF
WRITE (KLUN) SELF%XFRMIN
WRITE (KLUN) SELF%LNEWCOEFF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_RAIN_ICE_PARAM_T (SELF, KLUN)

IMPLICIT NONE
TYPE (RAIN_ICE_PARAM_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LXGAMINC_RIM1, LXGAMINC_RIM2, LXGAMINC_RIM4, LXKER_GWETH, LXKER_RACCS, LXKER_RACCSS, LXKER_RDRYG, LXKER_RWETH, LXKER_SACCRG, LXKER_SDRYG
LOGICAL :: LXKER_SWETH
READ (KLUN) SELF%XFSEDC
READ (KLUN) SELF%XFSEDR
READ (KLUN) SELF%XEXSEDR
READ (KLUN) SELF%XFSEDI
READ (KLUN) SELF%XEXCSEDI
READ (KLUN) SELF%XEXRSEDI
READ (KLUN) SELF%XFSEDS
READ (KLUN) SELF%XEXSEDS
READ (KLUN) SELF%XFSEDG
READ (KLUN) SELF%XEXSEDG
READ (KLUN) SELF%XNU10
READ (KLUN) SELF%XALPHA1
READ (KLUN) SELF%XBETA1
READ (KLUN) SELF%XNU20
READ (KLUN) SELF%XALPHA2
READ (KLUN) SELF%XBETA2
READ (KLUN) SELF%XMNU0
READ (KLUN) SELF%XALPHA3
READ (KLUN) SELF%XBETA3
READ (KLUN) SELF%XHON
READ (KLUN) SELF%XSCFAC
READ (KLUN) SELF%X0EVAR
READ (KLUN) SELF%X1EVAR
READ (KLUN) SELF%XEX0EVAR
READ (KLUN) SELF%XEX1EVAR
READ (KLUN) SELF%X0DEPI
READ (KLUN) SELF%X2DEPI
READ (KLUN) SELF%X0DEPS
READ (KLUN) SELF%X1DEPS
READ (KLUN) SELF%XEX0DEPS
READ (KLUN) SELF%XEX1DEPS
READ (KLUN) SELF%XRDEPSRED
READ (KLUN) SELF%X0DEPG
READ (KLUN) SELF%X1DEPG
READ (KLUN) SELF%XEX0DEPG
READ (KLUN) SELF%XEX1DEPG
READ (KLUN) SELF%XRDEPGRED
READ (KLUN) SELF%XTIMAUTI
READ (KLUN) SELF%XTEXAUTI
READ (KLUN) SELF%XCRIAUTI
READ (KLUN) SELF%XT0CRIAUTI
READ (KLUN) SELF%XACRIAUTI
READ (KLUN) SELF%XBCRIAUTI
READ (KLUN) SELF%XCOLIS
READ (KLUN) SELF%XCOLEXIS
READ (KLUN) SELF%XFIAGGS
READ (KLUN) SELF%XEXIAGGS
READ (KLUN) SELF%XTIMAUTC
READ (KLUN) SELF%XCRIAUTC
READ (KLUN) SELF%XFCACCR
READ (KLUN) SELF%XEXCACCR
READ (KLUN) SELF%XDCSLIM
READ (KLUN) SELF%XCOLCS
READ (KLUN) SELF%XEXCRIMSS
READ (KLUN) SELF%XCRIMSS
READ (KLUN) SELF%XEXCRIMSG
READ (KLUN) SELF%XCRIMSG
READ (KLUN) SELF%XEXSRIMCG
READ (KLUN) SELF%XSRIMCG
READ (KLUN) SELF%XEXSRIMCG2
READ (KLUN) SELF%XSRIMCG2
READ (KLUN) SELF%XSRIMCG3
READ (KLUN) SELF%XGAMINC_BOUND_MIN
READ (KLUN) SELF%XGAMINC_BOUND_MAX
READ (KLUN) SELF%XRIMINTP1
READ (KLUN) SELF%XRIMINTP2
READ (KLUN) SELF%NGAMINC
READ (KLUN) LXGAMINC_RIM1
IF (LXGAMINC_RIM1) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XGAMINC_RIM1 (IL1(1):IU1(1)))
  READ (KLUN) SELF%XGAMINC_RIM1
ENDIF
READ (KLUN) LXGAMINC_RIM2
IF (LXGAMINC_RIM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XGAMINC_RIM2 (IL1(1):IU1(1)))
  READ (KLUN) SELF%XGAMINC_RIM2
ENDIF
READ (KLUN) LXGAMINC_RIM4
IF (LXGAMINC_RIM4) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XGAMINC_RIM4 (IL1(1):IU1(1)))
  READ (KLUN) SELF%XGAMINC_RIM4
ENDIF
READ (KLUN) SELF%XFRACCSS
READ (KLUN) SELF%XLBRACCS1
READ (KLUN) SELF%XLBRACCS2
READ (KLUN) SELF%XLBRACCS3
READ (KLUN) SELF%XFSACCRG
READ (KLUN) SELF%XLBSACCR1
READ (KLUN) SELF%XLBSACCR2
READ (KLUN) SELF%XLBSACCR3
READ (KLUN) SELF%XACCLBDAS_MIN
READ (KLUN) SELF%XACCLBDAS_MAX
READ (KLUN) SELF%XACCLBDAR_MIN
READ (KLUN) SELF%XACCLBDAR_MAX
READ (KLUN) SELF%XACCINTP1S
READ (KLUN) SELF%XACCINTP2S
READ (KLUN) SELF%XACCINTP1R
READ (KLUN) SELF%XACCINTP2R
READ (KLUN) SELF%NACCLBDAS
READ (KLUN) SELF%NACCLBDAR
READ (KLUN) LXKER_RACCSS
IF (LXKER_RACCSS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_RACCSS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_RACCSS
ENDIF
READ (KLUN) LXKER_RACCS
IF (LXKER_RACCS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_RACCS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_RACCS
ENDIF
READ (KLUN) LXKER_SACCRG
IF (LXKER_SACCRG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_SACCRG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_SACCRG
ENDIF
READ (KLUN) SELF%XFSCVMG
READ (KLUN) SELF%XCOLIR
READ (KLUN) SELF%XEXRCFRI
READ (KLUN) SELF%XRCFRI
READ (KLUN) SELF%XEXICFRR
READ (KLUN) SELF%XICFRR
READ (KLUN) SELF%XFCDRYG
READ (KLUN) SELF%XCOLIG
READ (KLUN) SELF%XCOLEXIG
READ (KLUN) SELF%XFIDRYG
READ (KLUN) SELF%XFIDRYG2
READ (KLUN) SELF%XEXFIDRYG
READ (KLUN) SELF%XCOLSG
READ (KLUN) SELF%XCOLEXSG
READ (KLUN) SELF%XFSDRYG
READ (KLUN) SELF%XLBSDRYG1
READ (KLUN) SELF%XLBSDRYG2
READ (KLUN) SELF%XLBSDRYG3
READ (KLUN) SELF%XFRDRYG
READ (KLUN) SELF%XLBRDRYG1
READ (KLUN) SELF%XLBRDRYG2
READ (KLUN) SELF%XLBRDRYG3
READ (KLUN) SELF%XDRYLBDAR_MIN
READ (KLUN) SELF%XDRYLBDAR_MAX
READ (KLUN) SELF%XDRYLBDAS_MIN
READ (KLUN) SELF%XDRYLBDAS_MAX
READ (KLUN) SELF%XDRYLBDAG_MIN
READ (KLUN) SELF%XDRYLBDAG_MAX
READ (KLUN) SELF%XDRYINTP1R
READ (KLUN) SELF%XDRYINTP2R
READ (KLUN) SELF%XDRYINTP1S
READ (KLUN) SELF%XDRYINTP2S
READ (KLUN) SELF%XDRYINTP1G
READ (KLUN) SELF%XDRYINTP2G
READ (KLUN) SELF%NDRYLBDAR
READ (KLUN) SELF%NDRYLBDAS
READ (KLUN) SELF%NDRYLBDAG
READ (KLUN) LXKER_SDRYG
IF (LXKER_SDRYG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_SDRYG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_SDRYG
ENDIF
READ (KLUN) LXKER_RDRYG
IF (LXKER_RDRYG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_RDRYG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_RDRYG
ENDIF
READ (KLUN) SELF%XFSEDH
READ (KLUN) SELF%XEXSEDH
READ (KLUN) SELF%X0DEPH
READ (KLUN) SELF%X1DEPH
READ (KLUN) SELF%XEX0DEPH
READ (KLUN) SELF%XEX1DEPH
READ (KLUN) SELF%XCOLIH
READ (KLUN) SELF%XCOLEXIH
READ (KLUN) SELF%XCOLSH
READ (KLUN) SELF%XCOLEXSH
READ (KLUN) SELF%XCOLGH
READ (KLUN) SELF%XCOLEXGH
READ (KLUN) SELF%XFWETH
READ (KLUN) SELF%XFSWETH
READ (KLUN) SELF%XLBSWETH1
READ (KLUN) SELF%XLBSWETH2
READ (KLUN) SELF%XLBSWETH3
READ (KLUN) SELF%XFGWETH
READ (KLUN) SELF%XLBGWETH1
READ (KLUN) SELF%XLBGWETH2
READ (KLUN) SELF%XLBGWETH3
READ (KLUN) SELF%XFRWETH
READ (KLUN) SELF%XLBRWETH1
READ (KLUN) SELF%XLBRWETH2
READ (KLUN) SELF%XLBRWETH3
READ (KLUN) SELF%XWETLBDAS_MIN
READ (KLUN) SELF%XWETLBDAS_MAX
READ (KLUN) SELF%XWETLBDAG_MIN
READ (KLUN) SELF%XWETLBDAG_MAX
READ (KLUN) SELF%XWETLBDAR_MIN
READ (KLUN) SELF%XWETLBDAR_MAX
READ (KLUN) SELF%XWETLBDAH_MIN
READ (KLUN) SELF%XWETLBDAH_MAX
READ (KLUN) SELF%XWETINTP1S
READ (KLUN) SELF%XWETINTP2S
READ (KLUN) SELF%XWETINTP1G
READ (KLUN) SELF%XWETINTP2G
READ (KLUN) SELF%XWETINTP1R
READ (KLUN) SELF%XWETINTP2R
READ (KLUN) SELF%XWETINTP1H
READ (KLUN) SELF%XWETINTP2H
READ (KLUN) SELF%NWETLBDAS
READ (KLUN) SELF%NWETLBDAG
READ (KLUN) SELF%NWETLBDAR
READ (KLUN) SELF%NWETLBDAH
READ (KLUN) LXKER_SWETH
IF (LXKER_SWETH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_SWETH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_SWETH
ENDIF
READ (KLUN) LXKER_GWETH
IF (LXKER_GWETH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_GWETH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_GWETH
ENDIF
READ (KLUN) LXKER_RWETH
IF (LXKER_RWETH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_RWETH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_RWETH
ENDIF
READ (KLUN) SELF%XFRMIN
READ (KLUN) SELF%LNEWCOEFF
END SUBROUTINE













END MODULE
