MODULE UTIL_ELEC_DESCR_T_MOD

USE MODD_ELEC_DESCR, ONLY : ELEC_DESCR_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_ELEC_DESCR_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_ELEC_DESCR_T
END INTERFACE







CONTAINS

SUBROUTINE ACDC_SAVE_ELEC_DESCR_T (SELF, KLUN)

IMPLICIT NONE
TYPE (ELEC_DESCR_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%XFC
WRITE (KLUN) SELF%XFR
WRITE (KLUN) SELF%XFI
WRITE (KLUN) SELF%XFS
WRITE (KLUN) SELF%XFG
WRITE (KLUN) SELF%XFH
WRITE (KLUN) SELF%XCXR
WRITE (KLUN) SELF%XECHARGE
WRITE (KLUN) SELF%LSEDIM_BEARD
END SUBROUTINE

SUBROUTINE ACDC_LOAD_ELEC_DESCR_T (SELF, KLUN)

IMPLICIT NONE
TYPE (ELEC_DESCR_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%XFC
READ (KLUN) SELF%XFR
READ (KLUN) SELF%XFI
READ (KLUN) SELF%XFS
READ (KLUN) SELF%XFG
READ (KLUN) SELF%XFH
READ (KLUN) SELF%XCXR
READ (KLUN) SELF%XECHARGE
READ (KLUN) SELF%LSEDIM_BEARD
END SUBROUTINE













END MODULE
