MODULE YOMRAIN_ICE
!this modules contains the arrays in which the data is saved for all blocks

USE PARKIND1

IMPLICIT NONE

LOGICAL :: LLSAVE = .FALSE.

INTEGER :: IGPBLKS
INTEGER :: JBLK

!$OMP THREADPRIVATE (JBLK)

LOGICAL :: LLALLOCATED = .FALSE.

!declare the variables whith an extra block dimension


REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZEXN
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZDZZ
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRHODJ
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRHODREF
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZEXNREF
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZPABST
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZCIT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZCLDFR
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZICLDFR
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZSSIO
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZSSIU
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZIFR
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZHLC_HRC
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZHLC_HCF
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZHLI_HRI
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZHLI_HCF
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZTHT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRVT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRCT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRRT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRIT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRST
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRGT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZTHS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRVS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRCS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRRS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRIS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRSS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRGS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZINPRC
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZINPRR
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZEVAP3D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZINPRS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZINPRG
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZINDEP
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRAINFR
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZSIGS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZBUDGETS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQPIT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQCT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQRT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQIT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQST
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQGT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQNIT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQPIS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQCS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQRS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQIS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQSS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQGS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQNIS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZEFIELDW
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZLATHAM_IAGGS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZSEA
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZTOWN
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZCONC3D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRHT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRHS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZINPRH
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :, :) :: ZZFPR
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQHT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZQHS
!======================
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PCIT_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PHLC_HRC_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PHLC_HCF_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PHLI_HRI_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PHLI_HCF_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PTHS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRVS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRCS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRRS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRIS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRSS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRGS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: PINPRC_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: PINPRR_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PEVAP3D_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: PINPRS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: PINPRG_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: PINDEP_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRAINFR_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: TBUDGETS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQCT_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQRT_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQIT_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQST_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQGT_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQPIS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQCS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQRS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQIS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQSS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQGS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQNIS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRHS_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: PINPRH_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :, :) :: PFPR_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQHT_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PQHS_OUT


END MODULE
